kind: pipeline
name: default

steps:
- name: build
  image: golang:1.14
  environment:
    CGO_ENABLED: "0"
  commands:
  - go test -v -cover ./...
  - go build

- name: publish_main
  image: plugins/ecr
  settings:
    registry:
     from_secret: aws_ecr_platform_east1
    repo: drone-registry-plugin
    tags:
      - ${DRONE_COMMIT:0:7}
  when:
    ref:
      - refs/heads/main

- name: publish_tag
  image: plugins/ecr
  settings:
    registry:
     from_secret: aws_ecr_platform_east1
    repo: drone-registry-plugin
    tags:
      - ${DRONE_COMMIT:0:7}
      - ${DRONE_TAG}
  when:
    ref:
      - refs/tags/[0-9].[0-9].[0-9]

trigger:
  event:
  - push
  - pull_request
  - tag
